### PR TITLE
Add a line at the end of the file

### PR DESCRIPTION
**Pull request by Hesham-Elrehaimy**
@Bontgoy

### CODE REVIEW

**Comment by Bontgoy** [comment]
Looks good :shipit:

**Comment by Bontgoy** [comment]
@Hesham-Elrehaimy you should be merging your pull request for each exercise and then working on a new feature branch each time

**Comment by Hesham-Elrehaimy** [comment]
@Bontgoy Thank you for pointing that out. I realized that after I looked at the pull request and found that it was made under the same branch. I'm trying to remove it so I can merge the old one and re-do the new one.

**Comment by Bontgoy** [comment]
Just go ahead and merge this now and just continue with the knowledge for the future.

**Comment by Hesham-Elrehaimy** [comment]
Okay, thank you.

**Pull request merged**
